# Use the official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=Clase3
ENV MYSQL_USER=briely
ENV MYSQL_PASSWORD=toor

# Expose the default MySQL port
EXPOSE 3306

# Add any custom initialization scripts (optional)
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Default command to run MySQL
CMD ["mysqld"]